# encoding: utf-8
"""
Regression test for a real cluster incident (maintenance.feature:276
"No splitbrain in maintenance mode after failover").

Root cause: pg_rewind copies files (including postgresql.auto.conf) from the
live primary. If the primary concurrently rewrites postgresql.auto.conf via
ALTER SYSTEM (e.g. changing synchronous_standby_names) while pg_rewind is
reading it, the target can end up with a torn/truncated copy — pg_rewind
itself still exits 0 ("Done!") because it only checks WAL consistency, not
config file integrity.

do_rewind() blindly trusts the pg_rewind exit code and reports success, so
pgconsul schedules PostgreSQL start through the return-to-cluster machine with the
corrupted postgresql.auto.conf. PostgreSQL refuses to start
("syntax error ... near token", "configuration file ... contains errors"),
every subsequent pg_rewind retry fails identically (its own preflight `-C
restore_command` check reads the same broken local file), max_rewind_retries
is exhausted, and the host is left in permanent rewind-failed state — a
lasting split-brain since the old primary never rejoins as a replica.
"""

from unittest.mock import MagicMock, patch

from src.pg import Postgres, PostgresConfig


def _make_config(pgdata) -> PostgresConfig:
    return PostgresConfig(
        conn_string='host=localhost port=5432 dbname=postgres user=postgres',
        working_dir=str(pgdata),
        recovery_filepath=str(pgdata / 'recovery.conf'),
        use_replication_slots=False,
        standalone_pooler=False,
        pooler_conn_timeout=1.0,
        pooler_addr='localhost',
        pooler_port=6432,
        postgres_timeout=5.0,
        iteration_timeout=5.0,
    )


def _make_postgres(pgdata) -> Postgres:
    mock_cmd = MagicMock()
    mock_cmd.list_clusters.return_value = []
    config = _make_config(pgdata)

    with patch('src.pg.psycopg2.connect') as mock_connect:
        fake_conn = MagicMock()
        fake_conn.cursor.return_value = MagicMock()
        mock_connect.return_value = fake_conn

        with patch.object(Postgres, 'get_role', return_value='replica'), \
             patch.object(Postgres, '_get_pgdata_path', return_value=str(pgdata)):
            pg = Postgres(config, mock_cmd)

    pg.pgdata = str(pgdata)
    return pg


class TestDoRewindDetectsCorruptedAutoConf:
    """
    do_rewind() must not report success (return 0) when pg_rewind exits 0
    but leaves postgresql.auto.conf torn/corrupted by a concurrent
    ALTER SYSTEM write on the source (race condition observed in
    maintenance.feature:276).
    """

    def test_rewind_success_with_torn_auto_conf_is_not_silently_trusted(self, tmp_path):
        pg = _make_postgres(tmp_path)

        # Simulate the torn read exactly as seen in the incident logs:
        # "Error: invalid line 4 ... synchronous_standby_names = 'AN"
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# Do not edit this file manually!\n"
            "# It will be overwritten by the ALTER SYSTEM command.\n"
            "archive_command = '/bin/false'\n"
            "synchronous_standby_names = 'AN\n"  # <- torn: missing closing quote
        )

        # pg_rewind itself reports success (exit code 0) — it only checks
        # WAL divergence, not config file integrity on the target.
        pg._cmd_manager.rewind.return_value = 0

        result = pg.do_rewind('pgconsul_postgresql2_1.pgconsul_pgconsul_net')

        # BUG (red): do_rewind() currently returns 0 (success) here even
        # though postgresql.auto.conf is corrupted and PostgreSQL will
        # refuse to start with FATAL: configuration file contains errors.
        assert result != 0, (
            'do_rewind() must detect a torn postgresql.auto.conf left behind '
            'by a concurrent ALTER SYSTEM write on the source and NOT report '
            'success — otherwise pgconsul proceeds to attach to primary with '
            'a broken config, permanently failing (real incident: '
            'maintenance.feature:276 "No splitbrain in maintenance mode '
            'after failover").'
        )

    def test_rewind_temporarily_removes_standby_signal_for_single_user_recovery(self, tmp_path):
        pg = _make_postgres(tmp_path)
        standby_signal = tmp_path / 'standby.signal'
        standby_signal.touch()
        pg._cmd_manager.rewind.return_value = 0

        assert pg.do_rewind('primary') == 0

        pg._cmd_manager.rewind.assert_called_once_with(str(tmp_path), 'primary')
        assert not standby_signal.exists()
        assert not (tmp_path / 'standby.signal.pgconsul-rewind').exists()

    def test_rewind_restores_standby_signal_after_failure(self, tmp_path):
        pg = _make_postgres(tmp_path)
        standby_signal = tmp_path / 'standby.signal'
        standby_signal.touch()
        pg._cmd_manager.rewind.return_value = 1

        assert pg.do_rewind('primary') == 1

        assert standby_signal.exists()


class TestIsPostgresqlAutoConfValid:
    """Unit tests for _is_postgresql_auto_conf_valid() — the guard that
    detects a torn/corrupted postgresql.auto.conf after pg_rewind."""

    def test_valid_file_returns_true(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# Do not edit this file manually!\n"
            "# It will be overwritten by the ALTER SYSTEM command.\n"
            "archive_command = '/bin/false'\n"
            "synchronous_standby_names = 'ANY 1(host1)'\n"
        )
        assert pg._is_postgresql_auto_conf_valid() is True

    def test_unbalanced_quotes_returns_false(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "synchronous_standby_names = 'AN\n"
        )
        assert pg._is_postgresql_auto_conf_valid() is False

    def test_missing_equals_returns_false(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "archive_command '/bin/false'\n"
        )
        assert pg._is_postgresql_auto_conf_valid() is False

    def test_empty_file_returns_true(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text('')
        assert pg._is_postgresql_auto_conf_valid() is True

    def test_comments_only_returns_true(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# comment line 1\n"
            "# comment line 2\n"
        )
        assert pg._is_postgresql_auto_conf_valid() is True

    def test_missing_file_returns_true(self, tmp_path):
        pg = _make_postgres(tmp_path)
        assert pg._is_postgresql_auto_conf_valid() is True


class TestRepairPostgresqlAutoConf:
    """Unit tests for _repair_postgresql_auto_conf() — the method that
    removes corrupted lines and atomically replaces the file."""

    def test_repair_removes_torn_line_keeps_valid(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# Do not edit this file manually!\n"
            "archive_command = '/bin/false'\n"
            "synchronous_standby_names = 'AN\n"
            "restore_command = 'cp /x/%f %p'\n"
        )
        result = pg._repair_postgresql_auto_conf()
        assert result is True
        content = auto_conf.read_text()
        assert "synchronous_standby_names = 'AN" not in content
        assert "archive_command = '/bin/false'" in content
        assert "restore_command = 'cp /x/%f %p'" in content

    def test_repair_removes_line_without_equals(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "archive_command = '/bin/false'\n"
            "garbage_no_equals\n"
        )
        result = pg._repair_postgresql_auto_conf()
        assert result is True
        content = auto_conf.read_text()
        assert 'garbage_no_equals' not in content
        assert "archive_command = '/bin/false'" in content

    def test_repair_preserves_comments(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# header comment\n"
            "synchronous_standby_names = 'AN\n"
            "# trailing comment\n"
        )
        result = pg._repair_postgresql_auto_conf()
        assert result is True
        content = auto_conf.read_text()
        assert '# header comment' in content
        assert '# trailing comment' in content
        assert "synchronous_standby_names = 'AN" not in content

    def test_repair_makes_file_valid(self, tmp_path):
        """After repair, _is_postgresql_auto_conf_valid must return True."""
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "archive_command = '/bin/false'\n"
            "synchronous_standby_names = 'AN\n"
        )
        assert pg._is_postgresql_auto_conf_valid() is False
        pg._repair_postgresql_auto_conf()
        assert pg._is_postgresql_auto_conf_valid() is True


class TestDoRewindRepairRetryCycle:
    """End-to-end test: do_rewind detects corruption, repairs it, and on
    the next call (simulating a retry) succeeds because the file is now valid."""

    def test_rewind_repairs_then_succeeds_on_retry(self, tmp_path):
        pg = _make_postgres(tmp_path)
        auto_conf = tmp_path / 'postgresql.auto.conf'
        auto_conf.write_text(
            "# Do not edit this file manually!\n"
            "archive_command = '/bin/false'\n"
            "synchronous_standby_names = 'AN\n"
        )
        pg._cmd_manager.rewind.return_value = 0

        # First call: detects corruption, repairs, returns 1 (retry signal).
        result1 = pg.do_rewind('pgconsul_postgresql3_1.pgconsul_pgconsul_net')
        assert result1 != 0
        assert pg._is_postgresql_auto_conf_valid() is True

        # Second call (retry): file is now valid, so do_rewind returns 0.
        result2 = pg.do_rewind('pgconsul_postgresql3_1.pgconsul_pgconsul_net')
        assert result2 == 0
