name: Full suite on PR

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable

jobs:
  mypy:
    uses: ./.github/workflows/docker-mypy.yml

  unit:
    uses: ./.github/workflows/docker-unit.yml

  behave:
    name: behave
    needs: [mypy, unit]
    if: success()
    uses: ./.github/workflows/docker-behave.yml

  jepsen:
    name: jepsen
    needs: [mypy, unit]
    if: success()
    uses: ./.github/workflows/docker-jepsen.yml
